#!/bin/bash
# branch-memory: SessionStart hook
# Assembles MEMORY.md from global + branch notes, consolidates merged branches.

INPUT=$(cat)
CWD=$(echo "$INPUT" | jq -r '.cwd // empty' 2>/dev/null)
[ -z "$CWD" ] && CWD="$PWD"

# Skip non-git directories silently
BRANCH=$(git -C "$CWD" rev-parse --abbrev-ref HEAD 2>/dev/null)
[ -z "$BRANCH" ] && exit 0

BRANCH_SAFE=$(echo "$BRANCH" | tr '/' '_')
PROJECT_KEY=$(echo "$CWD" | tr '/' '-')
MEMORY_DIR="$HOME/.claude/projects/${PROJECT_KEY}/memory"
TODAY=$(date '+%Y-%m-%d')

mkdir -p "$MEMORY_DIR/branches"

# Initialize source files if missing
BRANCH_FILE="$MEMORY_DIR/branches/${BRANCH_SAFE}.md"
GLOBAL_FILE="$MEMORY_DIR/global.md"

[ -f "$BRANCH_FILE" ] || touch "$BRANCH_FILE"
[ -f "$GLOBAL_FILE" ] || printf '# Global Notes\n(Cross-branch notes go here)\n' > "$GLOBAL_FILE"

# ── Merge consolidation ──────────────────────────────────────────────────────
CONSOLIDATED=()
while IFS= read -r MERGED; do
  MERGED=$(echo "$MERGED" | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')
  [ -z "$MERGED" ] && continue
  [ "$MERGED" = "$BRANCH" ] && continue

  MERGED_SAFE=$(echo "$MERGED" | tr '/' '_')
  MERGED_FILE="$MEMORY_DIR/branches/${MERGED_SAFE}.md"
  [ -f "$MERGED_FILE" ] || continue

  CONTENT=$(grep -v '^[[:space:]]*$' "$MERGED_FILE" 2>/dev/null)
  if [ -z "$CONTENT" ]; then
    rm -f "$MERGED_FILE"
    continue
  fi

  {
    printf '\n## Consolidated from `%s` (merged %s)\n' "$MERGED" "$TODAY"
    cat "$MERGED_FILE"
  } >> "$GLOBAL_FILE"

  rm -f "$MERGED_FILE"
  CONSOLIDATED+=("$MERGED")
done < <(git -C "$CWD" branch --merged HEAD 2>/dev/null | grep -v '^\*')

# ── Assemble MEMORY.md ───────────────────────────────────────────────────────
{
  printf '<!-- AUTO-GENERATED by branch-memory: do not edit directly -->\n'
  printf '<!-- Current branch : %s -->\n' "$BRANCH"
  printf '<!-- Cross-branch   → memory/global.md -->\n'
  printf '<!-- This branch    → memory/branches/%s.md -->\n\n' "$BRANCH_SAFE"

  cat "$GLOBAL_FILE"
  printf '\n---\n\n'
  cat "$BRANCH_FILE"

  printf '\n---\n\n'
  printf '## Session Startup\n\n'
  printf 'At the very start of your **first response** this session, output this block verbatim (before anything else):\n\n'
  printf '```\n'
  printf '[branch-memory] branch : %s\n' "$BRANCH"
  if [ ${#CONSOLIDATED[@]} -gt 0 ]; then
    for B in "${CONSOLIDATED[@]}"; do
      printf '[branch-memory] merged  : %s → global.md\n' "$B"
    done
  fi
  printf '[branch-memory] global  : %s\n' "$GLOBAL_FILE"
  printf '[branch-memory] branch  : %s\n' "$BRANCH_FILE"
  printf '```\n\n'
  printf '## Memory Protocol\n\n'
  printf 'Update memory **proactively during this session** — no need to be asked.\n\n'
  printf '| Situation | File to update |\n'
  printf '|-----------|----------------|\n'
  printf '| Bug fixed · feature shipped · decision made · TODO left | `memory/branches/%s.md` |\n' "$BRANCH_SAFE"
  printf '| Architecture insight · key path · project-wide pattern  | `memory/global.md` |\n\n'
  printf 'Append with: `- [%s] <one concise sentence>`\n' "$TODAY"
  printf 'Use Edit or Write tools on those files. Never edit MEMORY.md directly.\n'
} > "$MEMORY_DIR/MEMORY.md"

# ── UI output ─────────────────────────────────────────────────────────────────
printf '[branch-memory] branch: %s\n' "$BRANCH"
if [ ${#CONSOLIDATED[@]} -gt 0 ]; then
  for B in "${CONSOLIDATED[@]}"; do
    printf '[branch-memory] consolidated merged branch: %s → global.md\n' "$B"
  done
fi
printf '[branch-memory] loaded global : %s\n' "$GLOBAL_FILE"
printf '[branch-memory] loaded branch : %s\n' "$BRANCH_FILE"
printf '[branch-memory] context ready : %s\n' "$MEMORY_DIR/MEMORY.md"
